/* 
 * File:   MCAL_interrupt_config.h
 * Author: Ahmed Khaled
 *
 * Created on 07 ??????, 2023, 08:42 ?
 */

#ifndef MCAL_INTERRUPT_CONFIG_H

#define	MCAL_INTERRUPT_CONFIG_H


/* _____________________________ INCLUDES SECTION  ______________________________*/
#include "../MCAL_std_types.h"
#include "../std_libraries.h"
#include "pic18f4620.h"
#include "../GPIO/MCAL_gpio.h"

/* _____________________________ DEFINITIONS SECTION  ______________________________*/

#define INTERRUPT_FEATURE_ENABLE                    1U
#define INTERRUPT_FEATURE_PRIORITY_ENABLE           INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_FEATURE_INTX_ENABLE               INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE                INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define EUSART_TX_INTERRUPT_FEATURE_ENABLE          INTERRUPT_FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE_ENABLE          INTERRUPT_FEATURE_ENABLE
#define SPI_INTERRUPT_FEATURE_ENABLE                INTERRUPT_FEATURE_ENABLE


#define INTERRUPT_ENABLE        1
#define INTERRUPT_DISABLE       0
#define INTERRUPT_OCCUR         1
#define INTERRUPT_NOT_OCCUR     0
#if (INTERRUPT_FEATURE_PRIORITY_ENABLE==INTERRUPT_FEATURE_ENABLE)
#define HIGH_PRIORITY           1U
#define LOW_PRIORITY            0U  
#endif
/* _____________________________ MACRO FUNCTIONS SECTION  ______________________________*/



#if (INTERRUPT_FEATURE_PRIORITY_ENABLE==INTERRUPT_FEATURE_ENABLE)

#define INTERRUPT_GLOBAL_INTERRUPT_ENABLE()  (INTCONbits.GIE = 1)
#define INTERRUPT_GLOBAL_INTERRUPT_DISABLE() (INTCONbits.GIE = 0)
#define INTERRUPT_PRIORITY_ENABLE()  (RCONbits.IPEN = 1)
#define INTERRUPT_PRIORITY_DISABLE() (RCONbits.IPEN = 0)
#define INTERRUPT_GLOBAL_HIGH_PRIORITY_ENABLE()   (INTCONbits.GIEH = 1)
#define INTERRUPT_GLOBAL_HIGH_PRIORITY_DISABLE()  (INTCONbits.GIEH = 0)
#define INTERRUPT_GLOBAL_LOW_PRIORITY_ENABLE()    (INTCONbits.GIEL = 1)
#define INTERRUPT_GLOBAL_LOW_PRIORITY_DISABLE()   (INTCONbits.GIEL = 0)
#else
#define INTERRUPT_GLOBAL_INTERRUPT_ENABLE()  (INTCONbits.GIE = 1)
#define INTERRUPT_GLOBAL_INTERRUPT_DISABLE() (INTCONbits.GIE = 0)
#define INTERRUPT_PERIPHERAL_ENABLE()        (INTCONbits.PEIE = 1)
#define INTERRUPT_PERIPHERAL_DISABLE()       (INTCONbits.PEIE = 0)

#endif
/* _____________________________ INTERFACES SECTION  ______________________________*/

#endif	/* MCAL_INTERRUPT_CONFIG_H */

